<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ACER" ignored="0" name="Test2" tests="2" failures="2" timestamp="28 Oct 2020 05:32:12 GMT" time="0.108" errors="0">
  <testcase name="invokebrowser" time="0.019" classname="BaseClass.BaseClass">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at BaseClass.BaseClass.invokebrowser(BaseClass.java:49)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- invokebrowser -->
  <testcase name="test" time="0.036" classname="TestCases.Objects">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at BaseClass.BaseClass.openUrl(BaseClass.java:81)
at TestCases.Objects.test(Objects.java:37)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 16 stack frames]]>
    </failure>
  </testcase> <!-- test -->
</testsuite> <!-- Test2 -->
